PRESET_BASE: 'mainnet'

CONFIG_NAME: 'gnosis-pos-poc'

# Transition
TERMINAL_TOTAL_DIFFICULTY: 231707791542740786049188744689299064356246512
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: .inf

# Genesis
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 16
MIN_GENESIS_TIME: 1746703800
GENESIS_FORK_VERSION: 0x0000006f
GENESIS_DELAY: 300

ALTAIR_FORK_VERSION: 0x0100006f
ALTAIR_FORK_EPOCH: 0

BELLATRIX_FORK_VERSION: 0x0200006f
BELLATRIX_FORK_EPOCH: 0

CAPELLA_FORK_VERSION: 0x0300006f
CAPELLA_FORK_EPOCH: 0

DENEB_FORK_VERSION: 0x0400006f
DENEB_FORK_EPOCH: 0

ELECTRA_FORK_VERSION: 0x0500006f
ELECTRA_FORK_EPOCH: 948224

FULU_FORK_VERSION: 0x0600006f
FULU_FORK_EPOCH: .inf

# Time parameters
SECONDS_PER_SLOT: 5
SECONDS_PER_ETH1_BLOCK: 6
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 1024

# Validator cycle
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 16
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 2

# Fork choice
PROPOSER_SCORE_BOOST: 40
REORG_HEAD_WEIGHT_THRESHOLD: 20
REORG_PARENT_WEIGHT_THRESHOLD: 160
REORG_MAX_EPOCHS_SINCE_FINALIZATION: 2

# Deposit contract
DEPOSIT_CHAIN_ID: 102001010
DEPOSIT_NETWORK_ID: 102001010
DEPOSIT_CONTRACT_ADDRESS: 0xb97036A26259B7147018913bD58a774cf91acf25

# Networking
MAX_PAYLOAD_SIZE: 10485760
MAX_REQUEST_BLOCKS: 1024
EPOCHS_PER_SUBNET_SUBSCRIPTION: 256
MIN_EPOCHS_FOR_BLOCK_REQUESTS: 33024
TTFB_TIMEOUT: 5
RESP_TIMEOUT: 10
ATTESTATION_PROPAGATION_SLOT_RANGE: 32
MAXIMUM_GOSSIP_CLOCK_DISPARITY: 500
MESSAGE_DOMAIN_INVALID_SNAPPY: 0x00000000
MESSAGE_DOMAIN_VALID_SNAPPY: 0x01000000
SUBNETS_PER_NODE: 2
ATTESTATION_SUBNET_COUNT: 64
ATTESTATION_SUBNET_EXTRA_BITS: 0
ATTESTATION_SUBNET_PREFIX_BITS: 6

# Deneb
MAX_REQUEST_BLOCKS_DENEB: 128
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 16384
BLOB_SIDECAR_SUBNET_COUNT: 6
MAX_BLOBS_PER_BLOCK: 6
MAX_REQUEST_BLOB_SIDECARS: 768

# Electra
MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA: 128000000000
MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT: 64000000000
BLOB_SIDECAR_SUBNET_COUNT_ELECTRA: 2
MAX_BLOBS_PER_BLOCK_ELECTRA: 2
MAX_REQUEST_BLOB_SIDECARS_ELECTRA: 256

# Fulu
NUMBER_OF_COLUMNS: 128
NUMBER_OF_CUSTODY_GROUPS: 128
DATA_COLUMN_SIDECAR_SUBNET_COUNT: 128
MAX_REQUEST_DATA_COLUMN_SIDECARS: 16384
SAMPLES_PER_SLOT: 8
CUSTODY_REQUIREMENT: 4
VALIDATOR_CUSTODY_REQUIREMENT: 8
BALANCE_PER_ADDITIONAL_CUSTODY_GROUP: 32000000000
MAX_BLOBS_PER_BLOCK_FULU: 2
MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS: 16384

# EIP7732
MAX_REQUEST_PAYLOADS: 128





./build/bin/geth --metalayer --authrpc.jwtsecret  --http --http.api eth,net,web3 --authrpc.addr=127.0.0.1 --authrpc.port=8553 --authrpc.vhosts=* --datadir ~/gnosis-poc/metalayer/node-3/el --discovery.port 30305 --http.port 8547 --port 30305 --bootnodes enode://da29540f7dbaf23dfba79785a6a5bbf53b81a0596ba829de50820b7b7cd7109e8d614f01a1a39379f7dca8546ac5e07dcadd37333cd0ffb35a1630e29a59f3de@127.0.0.1:30303

./lodestar beacon --dataDir=../metalayer/node-1/cl --jwtSecret=../jwt-secret/jwt1.secret --execution.urls=http://127.0.0.1:8551 --network chiado --discv5=true --rest.port=4000 --rest=true --port=9001 --bootnodes enr:-Hy4QIf0Nb3qfubc81ix5F6uG4t3izq8_0WahbBS4Ki0QW2YMmx6rmXhWjSViupWRrX7nx8Jz3_4xSIW89zlhdJzZKgBgmlkgnY0iXNlY3AyNTZrMaEDcJuOlUhF184DrUrV2y0AXCNKIPr0yM2MECaUDB11wKKDdWRwgiMo --persistNetworkIdentity true --enr.ip 127.0.0.1 --enr.udp 9001  --discoveryPort 9001 --mdns true
./lodestar beacon --dataDir=../metalayer/node-2/cl --jwtSecret=../jwt-secret/jwt2.secret --execution.urls=http://127.0.0.1:8552 --network chiado --discv5=true --rest.port=4002 --rest=true --port=9002 --bootnodes enr:-Hy4QIf0Nb3qfubc81ix5F6uG4t3izq8_0WahbBS4Ki0QW2YMmx6rmXhWjSViupWRrX7nx8Jz3_4xSIW89zlhdJzZKgBgmlkgnY0iXNlY3AyNTZrMaEDcJuOlUhF184DrUrV2y0AXCNKIPr0yM2MECaUDB11wKKDdWRwgiMo --persistNetworkIdentity true --enr.ip 127.0.0.1 --enr.udp 9002  --discoveryPort 9002 --mdns true
./lodestar beacon --dataDir=../metalayer/node-3/cl --jwtSecret=../jwt-secret/jwt3.secret --execution.urls=http://127.0.0.1:8553 --network chiado --discv5=true --rest.port=4004 --rest=true --port=9003 --bootnodes enr:-Hy4QIf0Nb3qfubc81ix5F6uG4t3izq8_0WahbBS4Ki0QW2YMmx6rmXhWjSViupWRrX7nx8Jz3_4xSIW89zlhdJzZKgBgmlkgnY0iXNlY3AyNTZrMaEDcJuOlUhF184DrUrV2y0AXCNKIPr0yM2MECaUDB11wKKDdWRwgiMo --persistNetworkIdentity true --enr.ip 127.0.0.1 --enr.udp 9003  --discoveryPort 9003 --mdns true