PRESET_BASE: 'gnosis'

CONFIG_NAME: 'gnosis-pos-poc'

# Transition
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615

# Genesis
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 16
MIN_GENESIS_TIME: 1746165900
GENESIS_FORK_VERSION: 0x00000064
GENESIS_DELAY: 120

# Forking
ALTAIR_FORK_VERSION: 0x01000064
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x02000064
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x03000064
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_VERSION: 0x04000064
DENEB_FORK_EPOCH: 18446744073709551615
ELECTRA_FORK_VERSION: 0x05000064
ELECTRA_FORK_EPOCH: 18446744073709551615
FULU_FORK_VERSION: 0x06000064
FULU_FORK_EPOCH: 18446744073709551615

# Time parameters
SECONDS_PER_SLOT: 5
SECONDS_PER_ETH1_BLOCK: 6
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 1024

# Validator cycle
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 16
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 2

# Fork choice
PROPOSER_SCORE_BOOST: 40
REORG_HEAD_WEIGHT_THRESHOLD: 20
REORG_PARENT_WEIGHT_THRESHOLD: 160
REORG_MAX_EPOCHS_SINCE_FINALIZATION: 2

# Deposit contract
DEPOSIT_CHAIN_ID: 426153627
DEPOSIT_NETWORK_ID: 426153627
DEPOSIT_CONTRACT_ADDRESS: 0x0B98057eA310F4d31F2a452B414647007d1645d9

# Networking
MAX_PAYLOAD_SIZE: 10485760
MAX_REQUEST_BLOCKS: 1024
EPOCHS_PER_SUBNET_SUBSCRIPTION: 256
MIN_EPOCHS_FOR_BLOCK_REQUESTS: 33024
TTFB_TIMEOUT: 5
RESP_TIMEOUT: 10
ATTESTATION_PROPAGATION_SLOT_RANGE: 32
MAXIMUM_GOSSIP_CLOCK_DISPARITY: 500
MESSAGE_DOMAIN_INVALID_SNAPPY: 0x00000000
MESSAGE_DOMAIN_VALID_SNAPPY: 0x01000000
SUBNETS_PER_NODE: 2
ATTESTATION_SUBNET_COUNT: 64
ATTESTATION_SUBNET_EXTRA_BITS: 0
ATTESTATION_SUBNET_PREFIX_BITS: 6

# Deneb
MAX_REQUEST_BLOCKS_DENEB: 128
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 16384
BLOB_SIDECAR_SUBNET_COUNT: 6
MAX_BLOBS_PER_BLOCK: 2
MAX_REQUEST_BLOB_SIDECARS: 768

# Electra
MIN_PER_EPOCH_CHURN_LIMIT_ELECTRA: 128000000000
MAX_PER_EPOCH_ACTIVATION_EXIT_CHURN_LIMIT: 64000000000
BLOB_SIDECAR_SUBNET_COUNT_ELECTRA: 2
MAX_BLOBS_PER_BLOCK_ELECTRA: 2
MAX_REQUEST_BLOB_SIDECARS_ELECTRA: 256

# Fulu
NUMBER_OF_COLUMNS: 128
NUMBER_OF_CUSTODY_GROUPS: 128
DATA_COLUMN_SIDECAR_SUBNET_COUNT: 128
MAX_REQUEST_DATA_COLUMN_SIDECARS: 16384
SAMPLES_PER_SLOT: 8
CUSTODY_REQUIREMENT: 4
VALIDATOR_CUSTODY_REQUIREMENT: 8
BALANCE_PER_ADDITIONAL_CUSTODY_GROUP: 32000000000
MAX_BLOBS_PER_BLOCK_FULU: 2
MIN_EPOCHS_FOR_DATA_COLUMN_SIDECARS_REQUESTS: 16384

# EIP7732
MAX_REQUEST_PAYLOADS: 128
